#!/usr/bin/with-contenv bash

set -xe

exec s6-setuidgid $USER \
  sunshine \
    key_rightalt_to_key_win=enabled \
    origin_web_ui_allowed=wan \
    port=$SUNSHINE_PORT \
    file_apps=/etc/sunshine/apps.json \
    upnp=off