FROM registry.fedoraproject.org/fedora-minimal:latest

RUN set -x \
  \
  && microdnf install -y --setopt=install_weak_deps=False --best \
    bindfs \
    coreos-installer \
  \
  && microdnf clean all \
  && rm -rf \
    /var/cache \
    /var/log/*

ENTRYPOINT ["bash", "-c"]