ARG FEDORA_VERSION

# s6 from https://github.com/linuxserver/docker-baseimage-fedora/blob/master/Dockerfile
FROM localhost/rootfs-stage:$FEDORA_VERSION AS rootfs-stage

# This hack overlays fedora rootfs on top of the cuda UBI image
FROM scratch AS BASE
ARG ARCH
ARG CODE_VERSION
ARG HELM_VERSION
ARG JFS_VERSION

COPY --from=rootfs-stage /root-out/ /

RUN set -x \
  \
  && echo 'exclude=*.i386 *.i686' >> /etc/dnf.conf \
  && rpm --setcaps shadow-utils 2>/dev/null \
  && dnf install -y --setopt=install_weak_deps=False --best \
    \
    podman \
    containernetworking-plugins \
    passt \
    netavark \
    aardvark-dns \
    crun \
    fuse-overlayfs \
    \
    sudo \
    git-core \
    iproute-tc \
    iptables-nft \
    gzip \
    tar \
    xz \
    jq \
    procps-ng \
    which \
    lsof \
    strace \
    https://github.com/coder/code-server/releases/download/v$CODE_VERSION/code-server-$CODE_VERSION-$ARCH.rpm \
    kubernetes-client \
    rsync \
    unar \
    unzip \
    ldns-utils \
  --exclude \
    container-selinux \
  && dnf autoremove -y \
  && dnf clean all \
  && rm -rf /var/cache /var/log/dnf* /var/log/yum.* \
  \
  && curl -L -o helm.tar.gz \
    https://get.helm.sh/helm-v$HELM_VERSION-linux-$ARCH.tar.gz \
  && tar xzf helm.tar.gz -C /usr/local/bin --strip-components=1 linux-$ARCH/helm \
  && rm -f helm.tar.gz \
  \
  && curl -L -o /usr/local/bin/mc \
    https://dl.min.io/client/mc/release/linux-$ARCH/mc \
  && chmod +x /usr/local/bin/mc \
  \
  && curl -L -o jfs.tar.gz \
    https://github.com/juicedata/juicefs/releases/download/v$JFS_VERSION/juicefs-$JFS_VERSION-linux-$ARCH.tar.gz \
  && tar xzf jfs.tar.gz -C /usr/local/bin juicefs \
  && rm -f jfs.tar.gz \
  \
  && echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel

COPY /root /

ENV \
  S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0 \
  S6_BEHAVIOUR_IF_STAGE2_FAILS=2 \
  S6_VERBOSITY=1 \
  USER=podman \
  UID=1000 \
  HOME=/home/podman \
  LANG=C.UTF-8 \
  CODE_PORT=8080

ENTRYPOINT ["/init"]