# based on https://github.com/containers/podman/blob/main/contrib/podmanimage/stable/Containerfile
# replace iptables-legacy with iptables-nft
ARG FEDORA_VERSION=latest

FROM registry.fedoraproject.org/fedora:$FEDORA_VERSION
ARG CODE_VERSION=4.16.1
ARG USER=podman
ARG UID=1000
ARG ARCH=amd64

COPY custom.repo /etc/yum.repos.d/

RUN set -x \
  \
  && rpm --setcaps shadow-utils 2>/dev/null \
  && dnf install -y --setopt=install_weak_deps=False --best \
    ca-certificates \
    podman \
    fuse-overlayfs \
    git-core \
    iproute-tc \
    iptables-nft \
    gzip \
    tar \
    xz \
    jq \
    procps-ng \
    which \
    lsof \
    ldns-utils \
    https://github.com/coder/code-server/releases/download/v$CODE_VERSION/code-server-$CODE_VERSION-$ARCH.rpm \
    # kube client
    kubectl \
    helm \
  --exclude \
    container-selinux \
  && dnf autoremove -y \
  && dnf clean all \
  && rm -rf /var/cache /var/log/dnf* /var/log/yum.* \
  \
  && curl -L https://dl.min.io/client/mc/release/linux-amd64/mc -o /usr/local/bin/mc \
  && chmod +x /usr/local/bin/mc \
  \
  && useradd $USER -m -u $UID \
  && echo -e "$USER:100000:65536" | tee /etc/subuid /etc/subgid \
  && usermod -G wheel $USER \
  && echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel

COPY /root /

USER $USER
ENTRYPOINT [ "code-server" ]
