FROM docker.io/alpine:3.22.1@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1
ARG PACKAGE_VERSION

RUN set -x \
  \
  && wget -O - \
    'https://dl.cloudsmith.io/public/isc/stork-dev/rsa.BF2C56ECBA97B498.key' > /etc/apk/keys/stork-dev@isc-BF2C56ECBA97B498.rsa.pub \
  && wget -O - \
    "https://dl.cloudsmith.io/public/isc/stork-dev/config.alpine.txt?distro=alpine&arch=$(arch)&version=$(cat /etc/alpine-release)" >> /etc/apk/repositories \
  && apk add --no-cache \
    isc-stork-agent=~$PACKAGE_VERSION

ENTRYPOINT ["stork-agent"]