# References
# https://github.com/linuxserver/docker-baseimage-kasmvnc/blob/fedora38/Dockerfile
# https://github.com/linuxserver/docker-baseimage-fedora/blob/master/Dockerfile
# https://github.com/linuxserver/docker-webtop/blob/fedora-xfce/Dockerfile
# https://github.com/kasmtech/workspaces-core-images/blob/develop/dockerfile-kasm-core-fedora

FROM localhost/buildstage:latest AS buildstage
FROM localhost/rootfs-stage:latest AS rootfs-stage

FROM scratch AS BASE

COPY --from=rootfs-stage /root-out/ /
COPY --from=buildstage /build-out/ /
COPY custom.repo /etc/yum.repos.d/

RUN set -x \
  \
  && dnf install -y \
    https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
  && dnf install -y --setopt=install_weak_deps=False --best \
    ca-certificates \
    coreutils \
    curl \
    findutils \
    hostname \
    netcat \
    procps-ng \
    pciutils-libs \
    shadow \
    git-core \
    iproute-tc \
    iptables-nft \
    gzip \
    tar \
    xz \
    unar \
    unzip \
    jq \
    which \
    lsof \
    ldns-utils \
    sudo \
    vim-minimal \
    less \
    mesa-dri-drivers \
    mesa-libgbm \
    mesa-libGL \
    mesa-libOpenCL \
    mesa-va-drivers-freeworld \
    mesa-vdpau-drivers-freeworld \
    mesa-vulkan-drivers \
    xorg-x11-drv-amdgpu \
    vulkan \
    vulkan-tools \
    intel-media-driver \
    # https://koji.rpmfusion.org/koji/packageinfo?packageID=650
    # https://koji.rpmfusion.org/kojifiles/packages/mesa-freeworld/23.1.6/1.fc38/x86_64/mesa-va-drivers-freeworld-23.1.6-1.fc38.x86_64.rpm \
    # https://koji.rpmfusion.org/kojifiles/packages/mesa-freeworld/23.1.6/1.fc38/x86_64/mesa-vdpau-drivers-freeworld-23.1.6-1.fc38.x86_64.rpm \
    libva-utils \
    pulseaudio \
    pulseaudio-utils \
    util-linux \
    dbus-x11 \
    xauth \
    xkbcomp \
    xkeyboard-config \
    ffmpeg \
    libjpeg-turbo \
    libwebp \
    libXdmcp \
    libXfont2 \
    libxshmfence \
    pixman \
    strace \
    unzip \
    \
    # XFCE
    gtk-xfce-engine \
    Thunar \
    xfce4-appfinder \
    xfce4-datetime-plugin \
    xfce4-panel \
    xfce4-places-plugin \
    xfce4-pulseaudio-plugin \
    xfce4-session \
    xfce4-settings \
    xfce4-terminal \
    xfconf \
    xfdesktop \
    xfwm4 \
    glibc-all-langpacks \
    bash-completion \
    flatpak \
    glx-utils \
  \
  && dnf autoremove -y \
  && dnf clean all \
  && rm -rf /var/cache /var/log/dnf* /var/log/yum.* \
  \
  && echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel \
  && rm -f \
    /etc/xdg/autostart/xfce-polkit.desktop

COPY /root /

ENV \
  S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0 \
  S6_VERBOSITY=1 \
  USER=kasm-user \
  UID=1000 \
  HOME=/home/kasm-user \
  DISPLAY=:1 \
  DEVICE=/dev/dri/renderD128 \
  XDG_RUNTIME_DIR=/run/user/1000 \
  LANG=C.UTF-8

ENTRYPOINT ["/init"]
