# References
# https://github.com/linuxserver/docker-baseimage-kasmvnc/blob/fedora38/Dockerfile
# https://github.com/linuxserver/docker-baseimage-fedora/blob/master/Dockerfile
# https://github.com/linuxserver/docker-webtop/blob/fedora-xfce/Dockerfile
# https://github.com/kasmtech/workspaces-core-images/blob/develop/dockerfile-kasm-core-fedora

FROM localhost/buildstage:latest AS buildstage
FROM localhost/rootfs-stage:latest AS rootfs-stage

FROM scratch AS BASE
ARG SUNSHINE_VERSION=0.20.0

COPY --from=rootfs-stage /root-out/ /
COPY --from=buildstage /build-out/ /
COPY custom.repo /etc/yum.repos.d/

RUN set -x \
  \
  && dnf install -y \
    https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
  && dnf install -y --setopt=install_weak_deps=False --best \
    ca-certificates \
    coreutils \
    curl \
    findutils \
    hostname \
    netcat \
    procps-ng \
    pciutils-libs \
    shadow \
    git-core \
    iproute-tc \
    iptables-nft \
    gzip \
    tar \
    xz \
    jq \
    which \
    lsof \
    ldns-utils \
    sudo \
    vim-minimal \
    less \
    mesa-dri-drivers \
    mesa-libgbm \
    mesa-libGL \
    mesa-libOpenCL \
    mesa-va-drivers-freeworld \
    mesa-vdpau-drivers-freeworld \
    # https://koji.rpmfusion.org/koji/packageinfo?packageID=650
    # https://koji.rpmfusion.org/kojifiles/packages/mesa-freeworld/23.1.6/1.fc38/x86_64/mesa-va-drivers-freeworld-23.1.6-1.fc38.x86_64.rpm \
    # https://koji.rpmfusion.org/kojifiles/packages/mesa-freeworld/23.1.6/1.fc38/x86_64/mesa-vdpau-drivers-freeworld-23.1.6-1.fc38.x86_64.rpm \
    libva-utils \
    vulkan \
    vulkan-tools \
    libva-vdpau-driver \
    vdpauinfo \
    pulseaudio \
    pulseaudio-utils \
    util-linux \
    dbus-x11 \
    xauth \
    xkbcomp \
    xkeyboard-config \
    xorg-x11-drv-nvidia-libs \
    xorg-x11-drv-nvidia-cuda-libs \
    ffmpeg \
    libjpeg-turbo \
    libwebp \
    libXfont2 \
    libxshmfence \
    pixman \
    \
    # XFCE
    gtk-xfce-engine \
    Thunar \
    xfce4-appfinder \
    xfce4-datetime-plugin \
    xfce4-panel \
    xfce4-places-plugin \
    xfce4-pulseaudio-plugin \
    xfce4-session \
    xfce4-settings \
    xfce4-terminal \
    xfconf \
    xfdesktop \
    xfwm4 \
    \
    # custom
    https://github.com/LizardByte/Sunshine/releases/download/v$SUNSHINE_VERSION/sunshine-fedora-$(rpm -E %fedora)-amd64.rpm \
    brave-browser \
    steam \
    lutris \
    xdg-user-dirs \
  \
  && dnf autoremove -y \
  && dnf clean all \
  && rm -rf /var/cache /var/log/dnf* /var/log/yum.* \
  \
  && echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel \
  && rm -f \
    /etc/xdg/autostart/xfce-polkit.desktop

# Patch nvidia driver for sunshine
RUN set -x \
  \
  && git clone https://github.com/keylase/nvidia-patch.git nvidia-patch \
  # patch script forces check on nvidia-smi even if we are specifying a driver version
  # this is a hack to bypass it
  && touch /usr/bin/nvidia-smi \
  && ./nvidia-patch/patch.sh -d $(rpm -q --queryformat "%{VERSION}" xorg-x11-drv-nvidia-cuda-libs) \
  && ./nvidia-patch/patch-fbc.sh -d $(rpm -q --queryformat "%{VERSION}" xorg-x11-drv-nvidia-cuda-libs) \
  && rm -r \
    /usr/bin/nvidia-smi\
    nvidia-patch \
    /opt/nvidia

COPY /root /

ENV \
  S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0 \
  S6_VERBOSITY=1 \
  USER=kasm-user \
  UID=1000 \
  HOME=/home/kasm-user \
  XDG_RUNTIME_DIR=/tmp/.X11-unix \
  DISPLAY=:1 \
  DEVICE=/dev/dri/renderD128

ENTRYPOINT ["/init"]