FROM registry.fedoraproject.org/fedora-minimal:latest@sha256:608122b5bfe4abbb17348d1c13a54e0e210d383d02a4dfff518cadd041bb74d0

ARG RELEASE
ARG INTERNAL_CA_CERT

RUN set -x \
  \
  && mkdir -p /etc/pki/ca-trust/source/anchors \
  && echo -e "$INTERNAL_CA_CERT" > /etc/pki/ca-trust/source/anchors/ca-cert.pem \
  && update-ca-trust \
  && microdnf install -y \
    https://s3.amazonaws.com/mountpoint-s3-release/$(echo $RELEASE | 's/mountpoint-s3-//')/$(arch)/$RELEASE-$(arch).rpm \
  && microdnf clean all \
  && rm -rf \
    /var/cache \
    /var/log/*
