ARG VERSION
FROM docker.io/nousresearch/hermes-agent:$VERSION

ARG APPTAINER_VERSION

RUN curl -L -o apptainer.deb \
    https://github.com/apptainer/apptainer/releases/download/v$APPTAINER_VERSION/apptainer_$APPTAINER_VERSION-trixie+_$(dpkg --print-architecture).deb \
  \
  && apt update \
  && apt install -y --no-install-recommends \
    python3-pip \
    ./apptainer.deb \
  && rm -rf /var/lib/apt/lists/* apptainer.deb

RUN python3 -m venv .venv \
  && . .venv/bin/activate \
  && pip install mnemosyne-hermes \
  && mkdir -p plugins/memory/mnemosyne \
  && ln -sfn \
    "$(.venv/bin/python -c 'import pathlib, mnemosyne_hermes; print(pathlib.Path(mnemosyne_hermes.__file__).resolve().parent)')"/* \
    plugins/memory/mnemosyne/
