FROM docker.io/golang:alpine@sha256:b6ed3fd0452c0e9bcdef5597f29cc1418f61672e9d3a2f55bf02e7222c014abd as build
ARG VERSION

WORKDIR /go/src
RUN set -x \
  \
  && apk add --no-cache \
    git \
    make \
    bash \
    rsync \
  \
  && git clone --depth 1 -b $VERSION https://github.com/kubernetes/kubernetes.git \
  && cd kubernetes \
  && make \
    kube-apiserver \
    kube-controller-manager \
    kube-scheduler

FROM scratch

COPY --from=build /go/src/kubernetes/_output/bin/kube-apiserver /usr/local/bin/
COPY --from=build /go/src/kubernetes/_output/bin/kube-controller-manager /usr/local/bin/
COPY --from=build /go/src/kubernetes/_output/bin/kube-scheduler /usr/local/bin/