#!/usr/bin/with-contenv bash

set -xe

exec Xorg \
  -ac \
  -noreset \
  -novtswitch \
  -sharevts \
  +extension RANDR \
  +extension RENDER \
  +extension GLX \
  +extension XVideo \
  +extension DOUBLE-BUFFER \
  +extension SECURITY \
  +extension DAMAGE \
  +extension X-Resource \
  -extension XINERAMA -xinerama \
  +extension Composite +extension COMPOSITE \
  -dpms \
  -s off \
  -nolisten tcp \
  -iglx \
  -verbose \
  vt7 $DISPLAY