FROM quay.io/podman/stable:latest
ARG CODE_VERSION=4.14.1

RUN set -x \
  \
  && dnf install --setopt=install_weak_deps=False -y \
    podman-compose \
    git-core \
    iproute-tc \
    tar \
    xz \
    jq \
    https://github.com/coder/code-server/releases/download/v$CODE_VERSION/code-server-$CODE_VERSION-amd64.rpm \
  \
  && dnf clean all \
  && rm -rf /var/cache/yum

ENTRYPOINT [ "code-server" ]
