# based on https://github.com/containers/podman/blob/main/contrib/podmanimage/stable/Containerfile
# replace iptables-legacy with iptables-nft
ARG FEDORA_VERSION=latest

FROM registry.fedoraproject.org/fedora:$FEDORA_VERSION
ARG CODE_VERSION=4.14.1
ARG USER=podman

COPY containers.conf /etc/containers/containers.conf

RUN set -x \
  \
  && rpm --setcaps shadow-utils 2>/dev/null \
  && dnf install -y --setopt=install_weak_deps=False --best \
    ca-certificates \
    podman \
    fuse-overlayfs \
    git-core \
    iproute-tc \
    iptables-nft \
    tar \
    xz \
    jq \
    procps-ng \
    https://github.com/coder/code-server/releases/download/v$CODE_VERSION/code-server-$CODE_VERSION-amd64.rpm \
  --exclude \
    container-selinux \
  \
  && dnf autoremove -y \
  && dnf clean all \
  && rm -rf /var/cache /var/log/dnf* /var/log/yum.* \
  # configure for podman in container #
  && sed \
    -e 's|^#mount_program|mount_program|g' \
    -e '/additionalimage.*/a "/var/lib/shared",' \
    -e 's|^mountopt[[:space:]]*=.*$|mountopt = "nodev,fsync=0"|g' \
    /usr/share/containers/storage.conf > /etc/containers/storage.conf \
  \
  && useradd $USER -u 1000 \
  && echo -e "$USER:100000:64535" > /etc/subuid \
  && echo -e "$USER:100000:64535" > /etc/subgid \
  && mkdir -p /home/$USER \
  && chown $USER:$USER -R /home/$USER \
  && usermod -G wheel $USER \
  && echo '%wheel ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/wheel \
  && mkdir -p \
    /var/lib/shared/overlay-images \
    /var/lib/shared/overlay-layers \
    /var/lib/shared/vfs-images \
    /var/lib/shared/vfs-layers \
  && touch \
    /var/lib/shared/overlay-images/images.lock \
    /var/lib/shared/overlay-layers/layers.lock \
    /var/lib/shared/vfs-images/images.lock \
    /var/lib/shared/vfs-layers/layers.lock

USER $USER
ENV _CONTAINERS_USERNS_CONFIGURED=""

ENTRYPOINT [ "code-server" ]
