FROM registry.fedoraproject.org/fedora-minimal:latest

RUN set -x \
  \
  && microdnf install -y \
    https://s3.amazonaws.com/mountpoint-s3-release/latest/x86_64/mount-s3.rpm \
  && microdnf clean all \
  && rm -rf \
    /var/cache \
    /var/log/*

ENTRYPOINT ["mount-s3"]