#!/usr/bin/with-contenv bash

set -xe

mkdir -p $HOME/nvidia

VERSION=$(nvidia-smi --query-gpu=driver_version --format=csv,noheader --id=0)
DRIVER_FILE=$HOME/nvidia/NVIDIA-Linux-$(arch)-${VERSION}.run

if [[ ! -f "$DRIVER_FILE" ]]; then
  curl -L -o $DRIVER_FILE \
    http://download.nvidia.com/XFree86/Linux-$(arch)/${VERSION}/NVIDIA-Linux-$(arch)-${VERSION}.run
fi

chmod +x $DRIVER_FILE

"$DRIVER_FILE" \
  --silent \
  --accept-license \
  --skip-depmod \
  --skip-module-unload \
  --no-kernel-modules \
  --no-kernel-module-source \
  --install-compat32-libs \
  --no-nouveau-check \
  --no-nvidia-modprobe \
  --no-systemd \
  --no-distro-scripts \
  --no-rpms \
  --no-backup \
  --no-check-for-alternate-installs \
  --no-libglx-indirect \
  --no-install-libglvnd

nvidia-xconfig \
  --virtual="${SIZE_W}x${SIZE_H}" \
  --depth="$COLOR_DEPTH" \
  --allow-empty-initial-configuration \
  --no-probe-all-gpus \
  --egpu \
  --no-sli \
  --no-base-mosaic \
  --only-one-x-screen \
  --use-display-device=$DISPLAY_DEVICE

modeline=$(cvt $SIZE_W $SIZE_H $REFRESH_RATE |grep -v ^#)

cat > /etc/X11/xorg.conf.d/20-custom.conf <<EOF
Section "OutputClass"
    Identifier "nvidia"
    Option     "ModeValidation" "NoMaxPClkCheck, NoEdidMaxPClkCheck, NoMaxSizeCheck, NoHorizSyncCheck, NoVertRefreshCheck, NoVirtualSizeCheck, NoTotalSizeCheck, NoDualLinkDVICheck, NoDisplayPortBandwidthCheck, AllowNon3DVisionModes, AllowNonHDMI3DModes, AllowNonEdidModes, NoEdidHDMI2Check, AllowDpInterlaced"
EndSection

Section "Monitor"
    Identifier "Monitor0"
    $modeline
    Option     "PreferredMode" $(echo $modeline | awk '{print $2}')
EndSection

Section "Screen"
    Identifier    "Screen0"
    Monitor       "Monitor0"
    Option        "ConnectedMonitor" "$DISPLAY_DEVICE"
    SubSection    "Display"
        Modes     $(echo $modeline | awk '{print $2}')
    EndSubSection
EndSection
EOF