FROM docker.io/alpine:latest as build
ARG VERSION=1.3.1

RUN set -x \
  \
  && TARGETARCH=$(arch) \
  && TARGETARCH=${TARGETARCH/x86_64/amd64} && TARGETARCH=${TARGETARCH/aarch64/arm64} \
  \
  && wget -O opds.tar.gz \
    https://github.com/dubyte/dir2opds/releases/download/v$VERSION/dir2opds_${VERSION}_linux_$TARGETARCH.tar.gz \
  && tar xzf opds.tar.gz -C /usr/local/bin dir2opds \
  && rm opds.tar.gz

FROM scratch
COPY --from=build /usr/local/bin/dir2opds /

ENTRYPOINT ["/dir2opds"]