FROM docker.io/debian:testing-slim as build
ARG VERSION

RUN set -e \
  \
  && apt update \
  && apt install -y --no-install-recommends \
    git \
    build-essential \
    cmake \
    libssl-dev \
    libvulkan-dev \
    glslc \
    spirv-headers \
  \
  && git clone -b $VERSION --depth=1 https://github.com/unslothai/llama.cpp.git /llama.cpp

RUN set -e \
  \
  && cd /llama.cpp \
  && cmake -B build \
    -DBUILD_SHARED_LIBS=OFF \
    -DGGML_VULKAN=1 \
  && cmake --build build --config Release --target llama-server

FROM scratch

COPY --from=build /llama.cpp/build/bin/llama-server /bin/llama-server