FROM alpine:latest AS BUILD

ARG VERSION
ARG TARGETARCH

RUN set -x \
  \
  && wget -O wireproxy.tar.gz \
    https://github.com/pufferffish/wireproxy/releases/download/v$VERSION/wireproxy_linux_$TARGETARCH.tar.gz \
  && tar xzf wireproxy.tar.gz \
  && rm wireproxy.tar.gz

FROM scratch

COPY --from=BUILD /wireproxy /

ENTRYPOINT ["/wireproxy"]