ARG GO_VERSION
FROM golang:$GO_VERSION-alpine AS BUILD

ARG VERSION
WORKDIR /go/src

RUN set -x \
  \
  && apk add --no-cache \
    git \
  \
  && git clone -b $VERSION \
    https://github.com/akrylysov/bsimp.git \
  && cd bsimp \
  && CGO_ENABLED=0 GO111MODULE=on GOOS=linux go install -v -ldflags '-s -w'

FROM alpine:edge
COPY --from=BUILD /go/bin/* /usr/local/bin/

ENTRYPOINT [ "/usr/local/bin/bsimp" ]
