#!/usr/bin/with-contenv sh

exec rclone serve \
  webdav \
  :s3:$S3_MUSIC_RESOURCE \
  --addr=127.0.0.1:$WEBDAV_PORT \
  --s3-provider=$S3_PROVIDER \
  --s3-endpoint=$S3_ENDPOINT \
  --no-modtime \
  --read-only