#!/usr/bin/with-contenv bash

FILES=$(find /dev/dri -type c -print 2>/dev/null)

for i in $FILES
do
  vainfo --display drm --device ${i}
  if [ $? -ne 0 ]; then
    DRINODE="${i}"
  fi
done

if [ -z "${DRINODE}" ]; then
  exit 1
fi

exec s6-setuidgid $USER \
  sunshine \
    key_rightalt_to_key_win=enabled \
    adapter_name=$DRINODE \
    origin_web_ui_allowed=pc \
    upnp=off