#!/usr/bin/with-contenv bash

FILES=$(find /dev/dri/renderD* -type c -print 2>/dev/null)

for i in $FILES
do
  vainfo --display drm --device ${i}
  if [ $? -eq 0 ]; then
    DRINODE="${i}"
    break
  fi
done

if [ -z "${DRINODE}" ]; then
  exit 1
fi

exec s6-setuidgid $USER \
  sunshine \
    key_rightalt_to_key_win=enabled \
    adapter_name=$DRINODE \
    origin_web_ui_allowed=pc \
    port=$SUNSHINE_PORT \
    upnp=off