FROM golang:alpine AS build

ARG VERSION
WORKDIR /go/src

RUN set -x \
  \
  && apk add --no-cache \
    git \
    make \
    libcap \
    ca-certificates \
  \
  && git clone -b v$VERSION https://github.com/coredns/coredns.git \
  && cd coredns \
  && echo "mdns:github.com/openshift/coredns-mdns" >> plugin.cfg \
  && make \
  && setcap cap_net_bind_service=+ep coredns

FROM gcr.io/distroless/static-debian12:nonroot

COPY --from=build /go/src/coredns/coredns /
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

USER nonroot:nonroot
WORKDIR /
EXPOSE 53 53/udp
ENTRYPOINT ["/coredns"]