#!/usr/bin/with-contenv sh

set -e

# prevents podman error
# WARN[0000] "/" is not a shared mount
mount --make-rshared /

juicefs format \
  --storage minio \
  --bucket $JFS_MINIO_BUCKET \
  --access-key $JFS_MINIO_ACCESS_KEY_ID \
  --secret-key $JFS_MINIO_SECRET_ACCESS_KEY \
  sqlite3://$JFS_DB_PATH \
  $JFS_RESOURCE_NAME