ARG PYTHON_VERSION
FROM docker.io/python:$PYTHON_VERSION-slim
ARG VERSION

RUN set -x \
  \
  && apt update && apt install -y \
    libgtk-3-0 \
    libx11-xcb1 \
    libasound2 \
    xvfb \
    tini \
  \
  && rm -rf /var/lib/apt/lists/*

RUN set -x \
  \
  && pip install -U --no-cache-dir \
    "camoufox[geoip]==${VERSION}"

RUN python -m camoufox fetch

ENTRYPOINT ["tini", "--"]