FROM docker.io/python:slim
ARG VERSION

RUN set -x \
  \
  && apt update && apt install -y \
    libgtk-3-0 \
    libx11-xcb1 \
    libasound2 \
    xvfb \
  \
  && rm -rf /var/lib/apt/lists/*

RUN set -x \
  \
  && pip install --no-cache-dir \
    "camoufox[geoip]==${VERSION}" \
    playwright==1.53.0

RUN python -m camoufox fetch