#!/usr/bin/with-contenv bash

set -xe

mountpoint $(dirname $HOME)

mkdir -p $HOME
chown $UID:$UID $HOME

useradd $USER -d $HOME -m -u $UID
usermod -G wheel $USER
echo -e "$USER:100000:65536" | tee /etc/subuid /etc/subgid

s6-setuidgid $USER \
  cp -r /etc/skel/. $HOME

exec s6-setuidgid $USER code-server \
  --auth=none \
  --bind-addr=0.0.0.0:$CODE_PORT
