#!/usr/bin/with-contenv bash

set -e

mountpoint $(dirname $HOME)

mkdir -p $HOME
chown $UID:$UID $HOME

useradd $USER -d $HOME -m -u $UID
usermod -G wheel $USER
usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $USER

s6-setuidgid $USER \
  cp -r /etc/skel/. $HOME

exec s6-setuidgid $USER code-server \
  --auth=none \
  --bind-addr=0.0.0.0:$CODE_PORT
