#!/usr/bin/with-contenv bash

FILES=$(find /dev/dri/renderD* -type c -print 2>/dev/null)

for i in $FILES
do
  vainfo --display drm --device ${i}
  if [ $? -eq 0 ]; then
    DRINODE="${i}"
    break
  fi
done

if [ -z "${DRINODE}" ]; then
  exit 1
fi

exec s6-setuidgid $USER \
  /usr/local/bin/Xvnc $DISPLAY \
    -hw3d \
    -drinode $DRINODE \
    -PublicIP 127.0.0.1 \
    -disableBasicAuth \
    -SecurityTypes None \
    -AlwaysShared \
    -http-header Cross-Origin-Embedder-Policy=require-corp \
    -http-header Cross-Origin-Opener-Policy=same-origin \
    -geometry $RESOLUTION \
    -sslOnly 0 \
    -RectThreads 0 \
    -websocketPort 6901 \
    -interface 0.0.0.0 \
    -Log *:stdout:10
