#!/usr/bin/with-contenv bash

DEVICE=$(ls /dev/dri/renderD* | head -n 1)

exec s6-setuidgid $USER \
  /usr/local/bin/Xvnc $DISPLAY \
    -hw3d \
    -drinode $DEVICE \
    -PublicIP 127.0.0.1 \
    -disableBasicAuth \
    -SecurityTypes None \
    -AlwaysShared \
    -http-header Cross-Origin-Embedder-Policy=require-corp \
    -http-header Cross-Origin-Opener-Policy=same-origin \
    -geometry $RESOLUTION \
    -sslOnly 0 \
    -RectThreads 0 \
    -websocketPort 6901 \
    -interface 0.0.0.0 \
    -Log *:stdout:10
