#!/usr/bin/with-contenv bash

exec s6-setuidgid $USER \
  /usr/local/bin/Xvnc $DISPLAY \
    -hw3d \
    -PublicIP 127.0.0.1 \
    -drinode $DEVICE \
    -disableBasicAuth \
    -SecurityTypes None \
    -AlwaysShared \
    -http-header Cross-Origin-Embedder-Policy=require-corp \
    -http-header Cross-Origin-Opener-Policy=same-origin \
    -geometry 1920x1080 \
    -sslOnly 0 \
    -RectThreads 0 \
    -websocketPort 6901 \
    -interface 0.0.0.0 \
    -Log *:stdout:10