FROM docker.io/golang:alpine as build
ARG VERSION

WORKDIR /go/src
RUN set -x \
  \
  && apk add --no-cache \
    git \
    make \
    bash \
    rsync \
  \
  && git clone --depth 1 -b $VERSION https://github.com/kubernetes/kubernetes.git \
  && cd kubernetes \
  && make \
    kube-proxy

FROM docker.io/alpine:3.22

# nftables version should match version on host
COPY --from=build /go/src/kubernetes/_output/bin/kube-proxy /usr/local/bin/
RUN set -x \
  \
  && echo "http://dl-cdn.alpinelinux.org/alpine/v3.21/main" >> /etc/apk/repositories \
  && apk add --no-cache \
    conntrack-tools \
    nftables=~1.1.1 \
    iptables \
    ipset \
    kmod