FROM docker.io/alpine:latest as build

RUN set -x \
  \
  && apk add --no-cache \
    g++ \
    xz-dev \
    make \
    perl \
    bash \
    cdrkit \
    git \
    openssl \
    coreutils \
  \
  && git clone --depth=1 -b master https://github.com/ipxe/ipxe /ipxe

WORKDIR /ipxe/src
COPY config/ config/local/

ARG INTERNAL_CA_CERT

# TODO: support multiple archs
RUN set -x \
  \
  && echo -e "$INTERNAL_CA_CERT" > ca-cert.pem \
  && make \
    bin-$(arch)-efi/ipxe.efi \
    CERT=ca-cert.pem \
    TRUST=ca-cert.pem \
  \
  && mkdir -p /build \
  && mv bin-$(arch)-efi/*.efi /build/

FROM scratch
COPY --from=build /build/ .