FROM docker.io/alpine:latest as build
ARG VERSION

RUN set -x \
  \
  && apk add --no-cache \
    g++ \
    xz-dev \
    make \
    perl \
    bash \
    cdrkit \
    git \
    openssl \
    coreutils \
  \
  && git clone -b $VERSION --depth=1 https://github.com/ipxe/ipxe /ipxe \
  && cd /ipxe

WORKDIR /ipxe/src
COPY config/ config/local/

ARG INTERNAL_CA_CERT
ARG INTERNAL_CLIENT_CERT
ARG INTERNAL_CLIENT_KEY

RUN set -e \
  \
  && TARGETARCH=$(arch) \
  && TARGETARCH=${TARGETARCH/aarch64/arm64} \
  \
  && echo -e "$INTERNAL_CA_CERT" > ca.crt \
  && echo -e "$INTERNAL_CLIENT_CERT" > tls.crt \
  && echo -e "$INTERNAL_CLIENT_KEY" > tls.key \
  && make -j $(getconf _NPROCESSORS_ONLN) \
    bin-$TARGETARCH-efi/ipxe.efi \
    CERT=tls.crt \
    PRIVKEY=tls.key \
    TRUST=ca.crt \
  \
  && mkdir -p /build \
  && mv bin-$TARGETARCH-efi/*.efi /build/

FROM docker.io/busybox:stable-musl

WORKDIR /var/www
COPY --from=build --chown=www-data:www-data /build/ .
USER www-data

ENTRYPOINT [ "httpd", "-f", "-v" ]