ARG VERSION
FROM ghcr.io/randomcoww/kubernetes:base-$VERSION AS BASE

## kube-master
FROM scratch AS kube-master

COPY --from=BASE /usr/local/bin/kube-apiserver /usr/local/bin/
COPY --from=BASE /usr/local/bin/kube-controller-manager /usr/local/bin/
COPY --from=BASE /usr/local/bin/kube-scheduler /usr/local/bin/

## kube-proxy
FROM docker.io/alpine:edge AS kube-proxy

COPY --from=BASE /usr/local/bin/kube-proxy /usr/local/bin/
RUN set -x \
  \
  && apk add --no-cache \
    conntrack-tools \
    nftables \
    iptables \
    ipset \
    kmod
