FROM docker.io/alpine:latest
ARG VERSION

COPY buildconfig /usr/src/
RUN set -x \
  \
  && apk add --no-cache --virtual .build-deps \
    git \
    libnl3-dev \
    openssl-dev \
    linux-headers \
    make \
    g++ \
  \
  && cd /usr/src \
  && wget -O hostapd.tar.gz https://w1.fi/releases/hostapd-$VERSION.tar.gz \
  && tar xf hostapd.tar.gz --strip-components=1 -C . \
  && cd hostapd \
  && mv /usr/src/buildconfig .config \
  && cat defconfig >> .config \
  && make -j $(getconf _NPROCESSORS_ONLN) install \
  \
## cleanup
  && cd \
  && rm -rf /usr/src \
  \
  && runDeps="$( \
    scanelf --needed --nobanner --format '%n#p' --recursive /usr/local \
      | tr ',' '\n' \
      | sort -u \
      | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
  )" \
  && apk add --no-cache --virtual .hostapd-rundeps $runDeps \
  && apk del .build-deps

ENTRYPOINT ["hostapd"]