# Based on https://git.alpinelinux.org/aports/tree/main/hostapd/APKBUILD
FROM alpine:latest

ARG VERSION
COPY . .

RUN <<_EOF
set -xe

apk add --no-cache --virtual .build-deps \
  libnl3-dev \
  openssl-dev \
  linux-headers \
  make \
  g++ \
  patch

wget -O hostapd.tar.gz "https://w1.fi/releases/hostapd-$VERSION.tar.gz"
mkdir -p /usr/src/hostapd
tar xf hostapd.tar.gz --strip-components=1 -C /usr/src/hostapd
patch -Np0 -i /noscan.patch -d /usr/src/hostapd
rm hostapd.tar.gz
cd /usr/src/hostapd/hostapd

cp defconfig .config
cat >> .config <<EOT
CC ?= ${CC:-gcc}
CFLAGS += -I/usr/include/libnl3
LIBS += -L/usr/local/lib
CONFIG_RADIUS_SERVER=y
CONFIG_DRIVER_WIRED=y
CONFIG_DRIVER_NONE=y
CONFIG_DRIVER_NL80211=y
CONFIG_DRIVER_NL80211_QCA=y
CONFIG_LIBNL32=y
CONFIG_IEEE80211N=y
CONFIG_IEEE80211AC=y
CONFIG_IEEE80211AX=y
CONFIG_IEEE80211R=y
CONFIG_FULL_DYNAMIC_VLAN=y
CONFIG_ACS=y
CONFIG_MBO=y
CONFIG_SAE=y
CONFIG_OWE=y
CONFIG_SUITEB192=y
EOT

make -j "$(getconf _NPROCESSORS_ONLN)" install

## cleanup
cd /
rm -rf /usr/src
apk add --no-cache --virtual .hostapd-rundeps $( \
  scanelf --needed --nobanner --format '%n#p' --recursive /usr/local \
    | tr ',' '\n' \
    | sort -u \
    | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
)
apk del .build-deps
_EOF

ENTRYPOINT ["hostapd"]
