FROM docker.io/busybox:1.37.0-musl@sha256:254e6134b1bf813b34e920bc4235864a54079057d51ae6db9a4f2328f261c2ad

WORKDIR /var/www
COPY --chown=www-data:www-data www/ .
USER www-data

ENTRYPOINT [ "httpd", "-f", "-v" ]