FROM alpine:latest
ARG VERSION

WORKDIR /var/tftpboot

RUN set -x \
  \
  && apk add --no-cache \
    tftp-hpa \
  && wget -O ipxe.efi \
    http://boot.ipxe.org/ipxe.efi \
  && wget -O ipxe-shimx64.efi \
    https://github.com/ipxe/shim/releases/download/$VERSION/ipxe-shimx64.efi


ENTRYPOINT [ "in.tftpd", "--foreground", "--user", "nobody", "--secure", "/var/tftpboot" ]
