FROM docker.io/golang:alpine as build
ARG VERSION

WORKDIR /go/src

RUN set -x \
  \
  && apk add --no-cache \
    git \
    make \
    bash \
    perl \
  \
  && git clone -b $VERSION --depth=1 https://github.com/minio/minio.git minio \
  && cd minio \
  && make install

FROM docker.io/alpine:latest
COPY --from=build /go/bin/minio /usr/bin/
COPY --from=build /go/src/minio/dockerscripts/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
VOLUME ["/data"]
CMD ["minio"]
