FROM docker.io/golang:alpine as build
ARG VERSION

WORKDIR /go/src

RUN set -x \
  \
  && apk add --no-cache \
    git \
    make \
    bash \
    perl \
  \
  && git clone --depth=1 https://github.com/minio/minio.git minio \
  && cd minio \
  && make install

FROM docker.io/alpine:latest
COPY --from=build /go/bin/minio /usr/bin/
RUN set -x \
  \
  && adduser -D -H -u 1000 -s /sbin/nologin minio

USER 1000:1000
VOLUME ["/data"]
ENTRYPOINT ["minio"]
