ARG FEDORA_VERSION
FROM fedora:$FEDORA_VERSION AS BUILD

ARG VERSION
RUN <<_BUILD
#!/bin/bash
set -xe

dnf install -y --setopt=install_weak_deps=False \
  git-core

git clone -b v$VERSION \
  --recurse-submodules https://github.com/LizardByte/Sunshine.git /sunshine
cd /sunshine

chmod +x ./scripts/linux_build.sh
./scripts/linux_build.sh \
  --publisher-name='LizardByte' \
  --publisher-website='https://app.lizardbyte.dev' \
  --publisher-issue-url='https://app.lizardbyte.dev/support' \
  --sudo-off
dnf clean all
rm -rf /var/cache/yum
_BUILD

# output at /sunshine/build/cpack_artifacts/Sunshine.rpm

ARG FEDORA_VERSION
FROM registry.fedoraproject.org/fedora-minimal:$FEDORA_VERSION

ARG DRIVER_VERSION
COPY custom.repo /etc/yum.repos.d/
COPY --from=BUILD /sunshine/build/cpack_artifacts/Sunshine.rpm /

RUN set -x \
  \
  && echo 'exclude=*.i386 *.i686' >> /etc/dnf.conf \
  && microdnf install -y \
    https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
  \
  && microdnf install -y --setopt=install_weak_deps=False --best \
    kmod-nvidia-open-dkms-$DRIVER_VERSION \
    nvidia-driver-$DRIVER_VERSION \
    nvidia-driver-cuda-libs-$DRIVER_VERSION \
    nvidia-modprobe-$DRIVER_VERSION \
    libnvidia-fbc-$DRIVER_VERSION \
    libva-nvidia-driver \
    /Sunshine.rpm \
  \
  && microdnf clean all \
  && rm -rf \
    /var/cache \
    /var/log/*

ENTRYPOINT ["sunshine"]