ARG FEDORA_VERSION=39

FROM registry.fedoraproject.org/fedora-minimal:$FEDORA_VERSION
ARG VERSION
ARG DRIVER_VERSION
ARG TARGETARCH

COPY custom.repo /etc/yum.repos.d/

RUN set -x \
  \
  && echo 'exclude=*.i386 *.i686' >> /etc/dnf.conf \
  && microdnf install -y \
    https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
  \
  && microdnf install -y --setopt=install_weak_deps=False --best \
    kmod-nvidia-open-dkms-$DRIVER_VERSION \
    nvidia-driver-$DRIVER_VERSION \
    nvidia-driver-cuda-libs-$DRIVER_VERSION \
    nvidia-modprobe-$DRIVER_VERSION \
    libnvidia-fbc-$DRIVER_VERSION \
    libva-nvidia-driver \
    https://github.com/LizardByte/Sunshine/releases/download/v$VERSION/sunshine-fedora-$(rpm -E %fedora)-$TARGETARCH.rpm \
  \
  # patch breaks unless nvidia-smi can be read, but isn't required to work because driver version is passed in manually
  && touch /usr/bin/nvidia-smi \
  && curl -L -o master.tar.gz \
    https://github.com/keylase/nvidia-patch/archive/master.tar.gz \
  && tar xf master.tar.gz \
  && nvidia-patch-master/patch.sh -d $(rpm -q --queryformat "%{VERSION}" libnvidia-fbc) \
  && nvidia-patch-master/patch-fbc.sh -d $(rpm -q --queryformat "%{VERSION}" libnvidia-fbc) \
  && microdnf clean all \
  && rm -rf \
    /var/cache \
    /var/log/* \
    nvidia-patch-master \
    master.tar.gz \
    /opt/nvidia \
    /usr/bin/nvidia-smi

ENV \
  NVIDIA_VISIBLE_DEVICES=all \
  NVIDIA_DRIVER_CAPABILITIES=all

ENTRYPOINT ["sunshine"]