
ARG IMAGE_RELEASE
FROM ghcr.io/tailscale/tailscale:$IMAGE_RELEASE AS source

FROM docker.io/alpine:latest

COPY --from=source /usr/local/bin/tailscale /usr/local/bin/
COPY --from=source /usr/local/bin/tailscaled /usr/local/bin/
COPY --from=source /usr/local/bin/containerboot /usr/local/bin/

RUN set -x \
  \
  && apk add --no-cache \
    ca-certificates \
    iptables \
    iproute2 \
    ip6tables

ENTRYPOINT [ "containerboot" ]