
ARG IMAGE_RELEASE
FROM ghcr.io/tailscale/tailscale:$IMAGE_RELEASE AS source

FROM docker.io/alpine:3.22.1@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1

COPY --from=source /usr/local/bin/tailscale /usr/local/bin/
COPY --from=source /usr/local/bin/tailscaled /usr/local/bin/
COPY --from=source /usr/local/bin/containerboot /usr/local/bin/

RUN set -x \
  \
  && apk add --no-cache \
    ca-certificates \
    iptables \
    iproute2 \
    ip6tables

ENTRYPOINT [ "containerboot" ]