
FROM ghcr.io/tailscale/tailscale:v1.88.2@sha256:9d66a1c8922e174cd346c2776c7c6f4450589543d988ae1bb9cefd8de58fd6c2 AS source

FROM docker.io/alpine:3.22.1

COPY --from=source /usr/local/bin/tailscale /usr/local/bin/
COPY --from=source /usr/local/bin/tailscaled /usr/local/bin/
COPY --from=source /usr/local/bin/containerboot /usr/local/bin/

RUN set -x \
  \
  && apk add --no-cache \
    ca-certificates \
    iptables \
    iproute2 \
    ip6tables

ENTRYPOINT [ "containerboot" ]