FROM docker.io/node:22-bookworm-slim
ARG VERSION

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
ENV NODE_ENV=production

RUN set -x \
  \
  && npm install -g patchright@$VERSION \
  && patchright install \
    --with-deps \
    --force \
    chromium