FROM docker.io/node:slim as deps
ARG VERSION

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
ENV NODE_ENV=production

WORKDIR /app

RUN set -x \
  \
  && npx -y patchright@$VERSION install-deps chromium \
  \
  && rm -r $HOME/.npm \
  && apt clean \
  && rm -rf /var/lib/apt/lists/* \
  \
  && mkdir -p ${PLAYWRIGHT_BROWSERS_PATH} \
  && chown -R node:node . ${PLAYWRIGHT_BROWSERS_PATH}

USER node
RUN set -x \
  \
  && npm -y install patchright@$VERSION \
  && npx -y patchright@$VERSION install chromium \
  && npm cache clean --force