FROM docker.io/node:slim
ARG VERSION

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
ENV NODE_ENV=production

WORKDIR /app

RUN set -x \
  \
  && npm set prefix . \
  && npm install -g patchright@$VERSION \
  && bin/patchright install \
    --with-deps \
    --force \
    --no-shell \
    chromium \
  \
  && chown -R node:node . ${PLAYWRIGHT_BROWSERS_PATH}

USER node

ENTRYPOINT ["/app/bin/patchright", "run-server"]