#!/usr/bin/with-contenv bash

set -xe

mkdir -p $HOME $XDG_RUNTIME_DIR
chown $UID:$UID $HOME $XDG_RUNTIME_DIR

useradd $USER -d $HOME -m -u $UID
usermod -G wheel,video,input,render $USER

s6-setuidgid $USER \
  cp -r /etc/skel/. $HOME

# sunshine
s6-setuidgid $USER \
  sunshine --creds $SUNSHINE_USERNAME $SUNSHINE_PASSWORD

# flatpak
mount -t proc none /proc

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

s6-setuidgid $USER \
  flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

s6-setuidgid $USER \
  ln -snf $HOME/.local/share/flatpak/exports/share/applications $HOME/.local/share/applications/flatpak