name: hermes-mnemosyne build
on:
  workflow_dispatch:
  schedule:
  - cron: "0 12 * * 1"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  TARGET: hermes-mnemosyne
  # renovate: datasource=docker depName=docker.io/nousresearch/hermes-agent versioning=regex:^v(?<major>\d+).(?<minor>\d+).(?<patch>\d+)$
  HERMES_VERSION: v2026.7.7

jobs:
  build:
    runs-on: kaniko-${{ github.event.repository.name }}
    container:
      image: ghcr.io/osscontainertools/kaniko:v1.28.1-debug@sha256:75e83052c3a0f4dd80285fdac0f5fceda6192c4404296539b8be0c5ec9b8d359
    permissions:
      contents: read
      packages: write
    steps:
    - name: Build and release container
      run: |
        set -e
        cat > $DOCKER_CONFIG/config.json <<EOF
        {
          "auths": {
            "ghcr.io": {
              "auth": "$(echo -n ${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }} | base64 -w0)"
            }
          }
        }
        EOF

        executor \
          --context-sub-path="$TARGET" \
          --dockerfile="./Containerfile" \
          --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
          --destination="$INTERNAL_REGISTRY/${{ github.repository_owner }}/${{ env.TARGET }}:$(echo $HERMES_VERSION | sed -r 's/@.+$//').$(date -u +%s)" \
          --registry-certificate=$INTERNAL_REGISTRY=$DOCKER_CONFIG/ca.crt \
          --registry-client-cert=$INTERNAL_REGISTRY=$DOCKER_CONFIG/client.cert,$DOCKER_CONFIG/client.key \
          --build-arg VERSION="$HERMES_VERSION" \
          --image-download-retry=4 \
          --image-fs-extract-retry=4 \
          --push-retry=4 \
          --snapshot-mode=redo \
          --use-new-run \
          --single-snapshot \
          --cleanup \
          --cache=false

  cleanup-internal:
    needs:
    - build
    env:
      TAGS_KEEP: 4
    runs-on: kaniko-${{ github.event.repository.name }}
    container:
      image: ghcr.io/regclient/regctl:v0.11.5-alpine@sha256:795e27a968ec0681cf1f4fd4bb83a880a1bc4698afb38efd5c961f9264820565
    steps:
    - name: Remove old tags
      run: |
        set -e
        tags=$(mktemp)
        repo=$INTERNAL_REGISTRY/${{ github.repository_owner }}/${{ env.TARGET }}
        regctl registry set $INTERNAL_REGISTRY --tls enabled \
          --cacert "$(cat $DOCKER_CONFIG/ca.crt)" \
          --client-cert "$(cat $DOCKER_CONFIG/client.cert)" \
          --client-key "$(cat $DOCKER_CONFIG/client.key)"

        for tag in $(regctl tag ls $repo --exclude latest); do
          regctl image config $repo:$tag --format "{{ printf \"$tag|%d\\n\" .Created.Unix }}" >> $tags
        done
        for tag in $(sort -k2 -t "|" -n $tags | head -n -$TAGS_KEEP); do
          regctl tag delete --ignore-missing $repo:$(echo $tag | cut -d "|" -f 1)
        done