name: ipxe build
on:
  workflow_dispatch:
  schedule:
  - cron: "0 14 * * 1"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  TARGET: ipxe
  REVISION: e80818e4f6e3791ec8240bda0a72eef999e4bf26

jobs:
  build:
    runs-on: builder-${{ github.event.repository.name }}
    container:
      image: ghcr.io/osscontainertools/kaniko:v1.26.6-debug@sha256:d2170bed1affc9d886853691c5ae7aa36163f2643de42693eb890bad8d1763ad
    permissions:
      contents: read
      packages: write
    steps:
    - name: Build and release container
      run: |
        set -e
        cat > $DOCKER_CONFIG/config.json <<EOF
        {
          "auths": {
            "ghcr.io": {
              "auth": "$(echo -n ${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }} | base64 -w0)"
            }
          }
        }
        EOF
        echo -e "$INTERNAL_CA_CERT" > $DOCKER_CONFIG/internal.crt

        executor \
          --context-sub-path="$TARGET" \
          --dockerfile="./Containerfile" \
          --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
          --destination="ghcr.io/${{ github.repository_owner }}/${{ env.TARGET }}:v$(date -u +'%Y%m%d.%H%M%S')" \
          --registry-certificate=$INTERNAL_REGISTRY=$DOCKER_CONFIG/internal.crt \
          --build-arg INTERNAL_CA_CERT="$INTERNAL_CA_CERT" \
          --build-arg REVISION="$REVISION" \
          --image-download-retry=4 \
          --image-fs-extract-retry=4 \
          --push-retry=4 \
          --snapshot-mode=redo \
          --use-new-run \
          --single-snapshot \
          --cleanup \
          --cache=false

  cleanup:
    needs:
    - build
    runs-on: builder-${{ github.event.repository.name }}
    container:
      image: docker.io/node:current-alpine@sha256:18e02657e2a2cc3a87210ee421e9769ff28a1ac824865d64f74d6d2d59f74b6b
    permissions:
      packages: write
    steps:
    - name: Remove old container images
      uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5
      with:
        package-name: ${{ env.TARGET }}
        package-type: container
        min-versions-to-keep: 4
        ignore-versions: latest
        token: ${{ secrets.GITHUB_TOKEN }}