name: kube-proxy build
on:
  workflow_dispatch:
  schedule:
  - cron: "0 14 * * 1"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  TARGET: kube-proxy
  GITHUB_RELEASE: v1.34.1 # kubernetes/kubernetes

jobs:
  build:
    runs-on: builder-${{ github.event.repository.name }}
    container:
      image: registry.default/randomcoww/kaniko:latest@sha256:101988b1ba4848de6dfe50ee77a62fc3632dd8b2cf033673dabafe2be95ffe87
    permissions:
      contents: read
      packages: write
    steps:
    - name: Set tag
      run: |
        set -e
        echo TIMESTAMP=$(date -u +'%Y%m%d.%H%M') | tee -a "$GITHUB_ENV"

    - name: Build and release container
      run: |
        cat > $DOCKER_CONFIG/config.json <<EOF
        {
          "auths": {
            "ghcr.io": {
              "auth": "$(echo -n ${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }} | base64 -w0)"
            }
          }
        }
        EOF
        echo -e "$INTERNAL_CA_CERT" > $DOCKER_CONFIG/internal.crt

        executor \
          --context-sub-path="$TARGET" \
          --dockerfile="./Containerfile" \
          --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
          --destination="ghcr.io/${{ github.repository_owner }}/${{ env.TARGET }}:$GITHUB_RELEASE.$TIMESTAMP" \
          --registry-certificate=$INTERNAL_REGISTRY=$DOCKER_CONFIG/internal.crt \
          --build-arg VERSION=$GITHUB_RELEASE \
          --use-new-run \
          --skip-unused-stages \
          --snapshot-mode=redo \
          --cleanup \
          --image-download-retry=4 \
          --image-fs-extract-retry=4 \
          --push-retry=4
  cleanup:
    needs:
    - build
    runs-on: builder-${{ github.event.repository.name }}
    container:
      image: docker.io/node:current-alpine@sha256:b0d33ed19a912e1a18ceb83e139815233cd49c123fe025e67a7c506c93e3f728
    permissions:
      packages: write
    steps:
    - name: Remove old container images
      uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # v5
      with:
        package-name: ${{ env.TARGET }}
        package-type: container
        min-versions-to-keep: 4
        ignore-versions: latest
        token: ${{ secrets.GITHUB_TOKEN }}