name: nvidia-nemotron-3-super-120b-a12b-mxfp4-moe build
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  TARGET: nvidia-nemotron-3-super-120b-a12b-mxfp4-moe

jobs:
  build:
    runs-on: kaniko-${{ github.event.repository.name }}
    container:
      image: ghcr.io/osscontainertools/kaniko:v1.27.4-debug@sha256:a394e5bd9c75c93e207b3949f3d7f49fbe59f21ea91d96ba6939ddf6226233f8
    permissions:
      contents: read
    steps:
    - name: Build and release container
      run: |
        set -e

        executor \
          --context-sub-path="$TARGET" \
          --dockerfile="./Containerfile" \
          --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
          --destination="$INTERNAL_REGISTRY/${{ github.repository_owner }}/${{ env.TARGET }}:v$(date -u +%s)" \
          --registry-certificate=$INTERNAL_REGISTRY=$DOCKER_CONFIG/ca.crt \
          --registry-client-cert=$INTERNAL_REGISTRY=$DOCKER_CONFIG/client.cert,$DOCKER_CONFIG/client.key \
          --image-download-retry=4 \
          --image-fs-extract-retry=4 \
          --push-retry=4 \
          --snapshot-mode=redo \
          --use-new-run \
          --single-snapshot \
          --cleanup \
          --cache=false \
          --compressed-caching=false