name: sunshine-desktop build
on:
  workflow_dispatch:
  schedule:
  - cron: "0 12 * * 1"
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  TARGET: sunshine-desktop
  # renovate: datasource=github-releases depName=LizardByte/Sunshine
  SUNSHINE_VERSION: v2026.617.152807

jobs:
  build:
    runs-on: kaniko-${{ github.event.repository.name }}
    container:
      image: ghcr.io/osscontainertools/kaniko:v1.27.6-debug@sha256:9047d4477bea3db093de3362f1c948cc86421e8403b7a720e2d490fb5a8aa7b2
    permissions:
      contents: read
    steps:
    - name: Build and release container
      run: |
        set -e

        executor \
          --context-sub-path="$TARGET" \
          --dockerfile="./Containerfile" \
          --context="${{ github.repositoryUrl }}#${{ github.ref }}#${{ github.sha }}" \
          --destination="$INTERNAL_REGISTRY/${{ github.repository_owner }}/${{ env.TARGET }}:$SUNSHINE_VERSION.$(date -u +%s)" \
          --registry-certificate=$INTERNAL_REGISTRY=$DOCKER_CONFIG/ca.crt \
          --registry-client-cert=$INTERNAL_REGISTRY=$DOCKER_CONFIG/client.cert,$DOCKER_CONFIG/client.key \
          --build-arg PACKAGE_VERSION=$(echo $SUNSHINE_VERSION | tr -d 'v') \
          --image-download-retry=4 \
          --image-fs-extract-retry=4 \
          --push-retry=4 \
          --snapshot-mode=redo \
          --use-new-run \
          --single-snapshot \
          --cleanup \
          --cache=false

  cleanup-internal:
    needs:
    - build
    env:
      TAGS_KEEP: 4
    runs-on: kaniko-${{ github.event.repository.name }}
    container:
      image: ghcr.io/regclient/regctl:v0.11.5-alpine@sha256:795e27a968ec0681cf1f4fd4bb83a880a1bc4698afb38efd5c961f9264820565
    steps:
    - name: Remove old tags
      run: |
        set -e
        tags=$(mktemp)
        repo=$INTERNAL_REGISTRY/${{ github.repository_owner }}/${{ env.TARGET }}
        regctl registry set $INTERNAL_REGISTRY --tls enabled \
          --cacert "$(cat $DOCKER_CONFIG/ca.crt)" \
          --client-cert "$(cat $DOCKER_CONFIG/client.cert)" \
          --client-key "$(cat $DOCKER_CONFIG/client.key)"

        for tag in $(regctl tag ls $repo --exclude latest); do
          regctl image config $repo:$tag --format "{{ printf \"$tag|%d\\n\" .Created.Unix }}" >> $tags
        done
        for tag in $(sort -k2 -t "|" -n $tags | head -n -$TAGS_KEEP); do
          regctl tag delete --ignore-missing $repo:$(echo $tag | cut -d "|" -f 1)
        done